terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
<Nov 26 13:37:59.446957> BE_MPI (ERROR): The error message in the job record is as follows:
<Nov 26 13:37:59.447026> BE_MPI (ERROR):   "killed with signal 6"
